api_version = "2024-04"



[[extensions]]
type = "ui_extension"
name = "order-alpha"
handle = "order-alpha"

[[extensions.targeting]]
target = "customer-account.order-status.block.render"
module = "./src/Checkout.jsx"
export = "orderDetailsBlock"


[extensions.capabilities]
api_access = true
network_access = true

# [[extensions.metafields]]
# namespace = "my-namespace"
# key = "my-key"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
# [settings]
#   [[settings.fields]]
#   key = "banner_title"
#   type = "single_line_text_field"
#   name = "Banner title"
#   description = "Enter a title for the banner"
